--- #YAML:1.0
name: Catalyst-Controller-SOAP
abstract: Add SOAP features to the Catalyst Framework
version: 0.0.1
author:
  - Daniel Ruoso <daniel@ruoso.com>
license: perl
distribution_type: module
requires:
  XML::LibXML: 0
  Catalyst::Controller: 5.90017
  Class::C3: 0
  XML::Compile::SOAP: 2.03
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
resources:
  repository: http://people.debian.org/~ruoso/Catalyst-Controller-SOAP/
